repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --line-width
    - '88'
    - --indent
    - '2'
    - --preserve-quotes
  - id: pretty-format-toml
    args:
    - --autofix
  - id: pretty-format-ini
    args:
    - --autofix
    - --indent
    - '2'
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.267
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args:
    - "--line-length=88"
    - "--target-version=py38"

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.13.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black
